<?php

namespace App\Support;

use App\OfferRoutingFlow;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Validation\ValidationException;
use LeadMax\TrackYourStats\Offer\Rules\Geo;

final class OfferFlowRulePublisher
{
    /** Called inside the same transaction as saving the flow. */
    public static function publish(OfferRoutingFlow $flow, bool $replaceExisting = false): void
    {
        if (!Schema::hasColumn('rule', 'routing_flow_id')) {
            self::reject('Apply the offer-rule generation migration before creating individual rules.');
        }
        $steps = $flow->steps;
        $ids = array_column($steps, 'offer_id');
        if (in_array((int) $flow->fallback_offer_id, $ids, true)) {
            self::reject('For individual rules, choose a final fallback outside the flow’s offer list to avoid a redirect loop.');
        }

        // Serialize publishers sharing offers, including rows removed by this publication.
        $previous = DB::table('rule')->where('routing_flow_id', $flow->id)->pluck('offer_idoffer')->all();
        DB::table('offer')->whereIn('idoffer', array_unique(array_merge($ids, $previous, [(int) $flow->fallback_offer_id])))
            ->orderBy('idoffer')->lockForUpdate()->get();
        $existing = DB::table('rule')->whereIn('offer_idoffer', $ids)->where('type', 'geo')->lockForUpdate()->get();
        $countryRows = DB::table('country_list')->join('geo_rule', 'geo_rule.idgeo_rule', '=', 'country_list.geo_rule_idgeo_rule')
            ->whereIn('rule_idrule', $existing->pluck('idrule'))->get()->groupBy('rule_idrule');
        $matches = [];
        $matchingIds = [];
        foreach ($steps as $index => $step) {
            $redirect = $steps[$index + 1]['offer_id'] ?? (int) $flow->fallback_offer_id;
            foreach ($existing->where('offer_idoffer', $step['offer_id']) as $rule) {
                if (self::matches($rule, $countryRows->get($rule->idrule, collect())->all(), $step, $redirect)) {
                    $matchingIds[] = $rule->idrule;
                    // Prefer this flow's existing rule if more than one identical rule already exists.
                    if (!isset($matches[$step['offer_id']]) || (int) $rule->routing_flow_id === (int) $flow->id) {
                        $matches[$step['offer_id']] = $rule;
                    }
                    continue;
                }
                if ($rule->routing_flow_id && (int) $rule->routing_flow_id !== (int) $flow->id) {
                    self::reject("Offer #{$rule->offer_idoffer} already has a different rule generated by flow #{$rule->routing_flow_id}. Use separate offers or remove that generated rule first.");
                }
                if (!$rule->routing_flow_id && $rule->is_active && !$replaceExisting) {
                    self::reject("Offer #{$rule->offer_idoffer} already has an active GEO rule that differs from this step. Select ‘Deactivate existing GEO rules’ to replace its country routing, or edit that rule first.");
                }
            }
        }

        $redirects = [];
        foreach ($steps as $index => $step) {
            // All-country rows terminate country routing, including unknown locations.
            if (empty($step['allow_all_countries'])) {
                $redirects[$step['offer_id']] = $steps[$index + 1]['offer_id'] ?? (int) $flow->fallback_offer_id;
            }
        }
        self::assertNoCycles($flow, $ids, $redirects);

        if ($replaceExisting) {
            DB::table('rule')->whereIn('offer_idoffer', $ids)->where('type', 'geo')
                ->whereNull('routing_flow_id')->where('is_active', 1)->whereNotIn('idrule', $matchingIds)->update(['is_active' => 0]);
        }
        foreach (DB::table('rule')->where('routing_flow_id', $flow->id)->whereNotIn('offer_idoffer', $ids)->get() as $obsolete) {
            self::removeRule((int) $obsolete->idrule);
        }
        foreach ($steps as $index => $step) {
            $all = !empty($step['allow_all_countries']);
            if (isset($matches[$step['offer_id']])) {
                $match = $matches[$step['offer_id']];
                // Never adopt or rename someone else's rule. Remove only this flow's superseded copies.
                foreach (DB::table('rule')->where('routing_flow_id', $flow->id)->where('offer_idoffer', $step['offer_id'])->where('idrule', '!=', $match->idrule)->get() as $superseded) {
                    self::removeRule((int) $superseded->idrule);
                }
                if ((int) $match->routing_flow_id === (int) $flow->id) {
                    DB::table('rule')->where('idrule', $match->idrule)->update(['name' => self::ruleName($step)]);
                }
                continue;
            }
            $attributes = [
                'name' => self::ruleName($step),
                'offer_idoffer' => $step['offer_id'], 'type' => 'geo', 'deny' => 0, 'is_active' => 1,
                'redirect_offer' => $steps[$index + 1]['offer_id'] ?? (int) $flow->fallback_offer_id,
                'routing_flow_id' => $flow->id,
            ];
            $ruleId = DB::table('rule')->where('routing_flow_id', $flow->id)->where('offer_idoffer', $step['offer_id'])->value('idrule');
            if ($ruleId) DB::table('rule')->where('idrule', $ruleId)->update($attributes);
            else $ruleId = DB::table('rule')->insertGetId($attributes, 'idrule');
            $geoId = DB::table('geo_rule')->where('rule_idrule', $ruleId)->value('idgeo_rule');
            if (!$geoId) $geoId = DB::table('geo_rule')->insertGetId(['rule_idrule' => $ruleId], 'idgeo_rule');
            DB::table('country_list')->where('geo_rule_idgeo_rule', $geoId)->delete();
            $countries = $all ? ['ALL'] : $step['countries'];
            DB::table('country_list')->insert(array_map(fn ($code) => [
                'geo_rule_idgeo_rule' => $geoId, 'country_code' => $code,
                'country_name' => $code === 'ALL' ? 'All countries (including unknown)' : mb_substr(Geo::$countries[$code], 0, 45),
                'cap_status' => 0, 'cap' => 0,
            ], $countries));
        }
    }

    private static function matches(object $rule, array $rows, array $step, int $redirect): bool
    {
        if (!(int) $rule->is_active || (int) $rule->deny !== 0 || (int) $rule->redirect_offer !== $redirect || !empty($rule->cap_status)) return false;
        foreach ($rows as $row) {
            if (!empty($row->cap_status)) return false;
        }
        $actual = array_values(array_unique(array_map(fn ($row) => strtoupper(trim((string) $row->country_code)), $rows)));
        $expected = !empty($step['allow_all_countries']) ? ['ALL'] : array_values(array_unique($step['countries']));
        sort($actual); sort($expected);
        return $actual === $expected;
    }

    private static function ruleName(array $step): string
    {
        if (!empty($step['allow_all_countries'])) return 'All countries';
        $countries = array_values(array_unique($step['countries']));
        sort($countries);
        if (count($countries) <= 75) return implode(' ', $countries);
        return implode(' ', array_slice($countries, 0, 75)).' (+'.(count($countries) - 75).' countries)';
    }

    private static function assertNoCycles(OfferRoutingFlow $flow, array $ids, array $redirects): void
    {
        $edges = [];
        // Existing GEO rules outside the replacement set may send fallback clicks back into this flow.
        $rules = DB::table('rule')->where('type', 'geo')->where('is_active', 1)->whereNotIn('offer_idoffer', $ids)
            ->where(fn ($q) => $q->whereNull('routing_flow_id')->orWhere('routing_flow_id', '!=', $flow->id))->get();
        $allRuleIds = DB::table('country_list')->join('geo_rule', 'geo_rule.idgeo_rule', '=', 'country_list.geo_rule_idgeo_rule')
            ->where('country_code', 'ALL')->pluck('rule_idrule')->all();
        foreach ($rules as $rule) {
            if (!$rule->deny && in_array($rule->idrule, $allRuleIds)) continue;
            if ($rule->redirect_offer) $edges[(int) $rule->offer_idoffer][] = (int) $rule->redirect_offer;
        }
        foreach ($redirects as $from => $to) $edges[$from][] = $to;
        $visiting = []; $done = [];
        $visit = function ($id) use (&$visit, &$visiting, &$done, $edges) {
            if (isset($visiting[$id])) self::reject('Individual rules would create a GEO redirect loop. Change the final fallback or its existing redirects.');
            if (isset($done[$id])) return;
            $visiting[$id] = true;
            foreach ($edges[$id] ?? [] as $next) $visit($next);
            unset($visiting[$id]); $done[$id] = true;
        };
        foreach ($ids as $id) $visit($id);
    }

    private static function removeRule(int $id): void
    {
        $geoIds = DB::table('geo_rule')->where('rule_idrule', $id)->pluck('idgeo_rule');
        DB::table('country_list')->whereIn('geo_rule_idgeo_rule', $geoIds)->delete();
        DB::table('geo_rule')->where('rule_idrule', $id)->delete();
        DB::table('rule')->where('idrule', $id)->delete();
    }

    private static function reject(string $message): void
    {
        throw ValidationException::withMessages(['offer_rules' => $message]);
    }
}
